apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.grafana: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana"}}'
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-token
  annotations:
    kubernetes.io/service-account.name: grafana
type: kubernetes.io/service-account-token
